# Generated by Django 2.0.7 on 2018-08-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20180810_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.CharField(choices=[('CYCLE', 'Циклы')], default='Циклы', max_length=20),
        ),
    ]
